/**
 * Bearer-token auth middleware for the Jarvis MCP server.
 *
 * Tokens are generated by `mc-ctl mcp-token create --client <name>`, which
 * stores their SHA-256 hash in the `mcp_tokens` table. Raw bearer strings
 * are shown exactly once at creation time and never retrievable.
 *
 * Middleware behavior:
 *  - Parses `Authorization: Bearer <token>` header.
 *  - Computes SHA-256 of the token, looks up a non-revoked row.
 *  - On match: populates `c.get("mcpToken")` with `{id, clientName, scope}`
 *    and touches `last_used_at` (best-effort).
 *  - On miss or malformed header: returns 401.
 *
 * Never logs the raw token or its hash.
 */

import type { MiddlewareHandler } from "hono";
import { createHash } from "node:crypto";
import { getDatabase } from "../../db/index.js";
import type { McpTokenInfo } from "./types.js";

const BEARER_RE = /^Bearer\s+([A-Za-z0-9_-]+)$/;

export function mcpAuth(): MiddlewareHandler {
  return async (c, next) => {
    const header = c.req.header("Authorization") ?? "";
    const match = header.match(BEARER_RE);
    if (!match) {
      return c.json({ error: "missing_or_malformed_bearer" }, 401);
    }

    const tokenHash = createHash("sha256").update(match[1]).digest("hex");
    const row = getDatabase()
      .prepare(
        "SELECT id, client_name, scope FROM mcp_tokens WHERE token_hash = ? AND revoked = 0",
      )
      .get(tokenHash) as
      | { id: number; client_name: string; scope: "read_only" }
      | undefined;

    if (!row) {
      return c.json({ error: "invalid_or_revoked_token" }, 401);
    }

    // Best-effort last_used_at update; failure is non-fatal telemetry.
    try {
      getDatabase()
        .prepare(
          "UPDATE mcp_tokens SET last_used_at = datetime('now') WHERE id = ?",
        )
        .run(row.id);
    } catch {
      // Ignore — never block a request on a telemetry write.
    }

    const info: McpTokenInfo = {
      id: row.id,
      clientName: row.client_name,
      scope: row.scope,
    };
    c.set("mcpToken", info);
    await next();
    return;
  };
}
