/**
 * ai_overview_track — track AI Overview presence for a query on Google SERP.
 *
 * Uses the stealth browser to fetch the Google SERP, parses the HTML for
 * AI-Overview markers (text + DOM heuristics — markers change frequently so
 * we use multiple signals), extracts top-10 organic results + cited sources.
 *
 * Persists to `ai_overview_tracking` for time-series + attribution monitoring.
 *
 * Part of v7.3 Phase 3 — AI Overview Monitoring.
 *
 * Limitations (by design, v1):
 *   - Google heavily anti-bots SERP scraping. If stealth fetch is blocked
 *     (CF challenge, CAPTCHA, 429), the tool returns fetch_status="blocked"
 *     + a suggestion to provision SERP_API_KEY (SerpAPI fallback, follow-up).
 *   - AI-Overview DOM markers are obfuscated and change; detection uses text
 *     + structural heuristics that WILL drift. When inclusion rates vs Google
 *     Search Console clicks diverge, that's the signal to update heuristics.
 *   - No scheduled ritual wiring yet — this ships as a manually-callable
 *     tool. Schedule + alert on attribution loss is a v7.3 P3 follow-up.
 */

import type { Tool } from "../types.js";
import { getDatabase, writeWithRetry } from "../../db/index.js";
import { stealthFetch } from "../../lib/stealth-browser.js";

/**
 * Concurrency cap — each stealthFetch spawns a headless Chromium (~300MB RSS).
 * Without this, a scheduled ritual tracking 10 queries in parallel would fork
 * 10 browsers simultaneously. Serialize to at most 2 in-flight at a time.
 */
const MAX_CONCURRENT_SERP_FETCHES = 2;
let activeFetches = 0;
const fetchQueue: Array<() => void> = [];

async function acquireSerpSlot(): Promise<void> {
  if (activeFetches < MAX_CONCURRENT_SERP_FETCHES) {
    activeFetches++;
    return;
  }
  await new Promise<void>((resolve) => fetchQueue.push(resolve));
  activeFetches++;
}

function releaseSerpSlot(): void {
  activeFetches--;
  const next = fetchQueue.shift();
  if (next) next();
}

interface AIOverviewSource {
  title: string;
  url: string;
  rank: number;
}

interface SerpOrganicResult {
  title: string;
  url: string;
}

export interface AIOverviewResult {
  query: string;
  present: boolean;
  sources: AIOverviewSource[];
  serp_top: SerpOrganicResult[];
  fetch_status: "ok" | "blocked" | "empty" | "parse_error";
  detection_signal?: string; // which heuristic fired
  note?: string;
}

/** Multiple heuristic signals for AI Overview presence — any hit = present. */
function detectAIOverview(html: string): { present: boolean; signal?: string } {
  // Signal 1: structured-data attributes (most stable)
  if (/data-attrid=["']?AIOverview["']?/i.test(html)) {
    return { present: true, signal: "data-attrid=AIOverview" };
  }
  if (/data-attrid=["']?GPTW["']?/i.test(html)) {
    // Internal Google code name; sometimes appears
    return { present: true, signal: "data-attrid=GPTW" };
  }
  // Signal 2: aria-labeled block explicitly named AI Overview / SGE
  if (
    /aria-label=["'](?:AI Overview|AI overview|SGE[^"']*|Generative AI response)["']/i.test(
      html,
    )
  ) {
    return { present: true, signal: "aria-label:AI Overview" };
  }

  // Top portion of HTML — the AI Overview panel always sits at the very top
  // of SERP HTML (above organic results). Scoping to 20KB is tight enough to
  // exclude organic snippets from triggering the text heuristic. Round 1 used
  // 80KB which still included many organic results with `data-attrid=` cues.
  const top = html.slice(0, 20_000);

  // Signal 3: "AI Overview" label within 2000 chars of a structural cue in
  // the top 20KB. Proximity requirement (not just co-existence) prevents the
  // false-positive case where Google's top-bar widgets + a later organic
  // snippet mentioning "AI Overview" both live in the top slice.
  const proximityRe =
    /(?:role=["']region["']|jscontroller=\w+|data-attrid=["']?[A-Z])[\s\S]{0,2000}\bAI Overview\b|\bAI Overview\b[\s\S]{0,2000}(?:role=["']region["']|jscontroller=\w+|data-attrid=["']?[A-Z])/i;
  if (proximityRe.test(top)) {
    return { present: true, signal: "text:AI Overview (proximity+structural)" };
  }
  if (/Generated by Google AI/i.test(top)) {
    return { present: true, signal: "text:Generated by Google AI" };
  }
  if (/\bAI-generated (?:answer|overview|response)\b/i.test(top)) {
    return { present: true, signal: "text:AI-generated" };
  }

  // Signal 4: Generative-SGE hint classes (historical, obfuscated — low signal)
  if (/class=["'][^"']*\b(?:hdzaWe|AJOR0c|aPPdYe)\b/i.test(top)) {
    return { present: true, signal: "class:sge-marker" };
  }

  return { present: false };
}

/** Detect anti-bot interstitials (CAPTCHA, "unusual traffic", etc.). */
function detectBotBlock(html: string): boolean {
  return (
    /unusual traffic/i.test(html) ||
    /sorry\/index\?continue/i.test(html) ||
    /<title>[^<]*captcha[^<]*<\/title>/i.test(html) ||
    /__jr-id/.test(html) // Google sorry-page marker
  );
}

/** Rough organic-result extraction from Google SERP HTML. */
function extractOrganicResults(html: string): SerpOrganicResult[] {
  const out: SerpOrganicResult[] = [];
  const seen = new Set<string>();
  // Google wraps organic results in <a href="/url?q=..."> or direct https href
  // followed by an <h3> containing the title. Two regexes handle the two
  // shapes so we don't truncate direct URLs at `&` when they include query
  // strings like `?utm_source=...&foo=bar`.
  const googleWrappedRe =
    /<a[^>]+href=["']\/url\?q=(https?:\/\/[^"'&]+)[^"']*["'][^>]*>[\s\S]{0,500}?<h3[^>]*>([\s\S]{1,200}?)<\/h3>/gi;
  const directRe =
    /<a[^>]+href=["'](https?:\/\/[^"']+)["'][^>]*>[\s\S]{0,500}?<h3[^>]*>([\s\S]{1,200}?)<\/h3>/gi;
  for (const re of [googleWrappedRe, directRe]) {
    let m: RegExpExecArray | null;
    while ((m = re.exec(html)) !== null && out.length < 10) {
      let url: string;
      try {
        url = decodeURIComponent(m[1]);
      } catch {
        continue;
      }
      if (seen.has(url)) continue;
      if (/^https?:\/\/(?:www\.)?google\./i.test(url)) continue;
      const title = m[2]
        .replace(/<[^>]+>/g, "")
        .replace(/\s+/g, " ")
        .trim();
      if (!title) continue;
      seen.add(url);
      out.push({ url, title });
    }
  }
  return out;
}

/** Best-effort extraction of sources cited inside the AI Overview block. */
function extractAIOverviewSources(html: string): AIOverviewSource[] {
  const out: AIOverviewSource[] = [];
  // Pragmatic heuristic: find the AI-Overview region by signal, then scan the
  // next ~15kb for anchor hrefs pointing off-Google. This is a best-effort —
  // misses will just yield an empty sources[] array.
  const markers = [
    /data-attrid=["']?AIOverview["']?/i,
    /\bAI Overview\b/i,
    /Generated by Google AI/i,
  ];
  let regionStart = -1;
  for (const m of markers) {
    const match = html.match(m);
    if (match?.index !== undefined) {
      regionStart = match.index;
      break;
    }
  }
  if (regionStart < 0) return out;
  const region = html.slice(regionStart, regionStart + 15000);
  const hrefRe = /href=["'](https?:\/\/[^"']+)["']/gi;
  const seen = new Set<string>();
  let rank = 0;
  let m: RegExpExecArray | null;
  while ((m = hrefRe.exec(region)) !== null && out.length < 10) {
    const url = m[1];
    if (/^https?:\/\/(?:www\.)?google\./i.test(url)) continue;
    if (seen.has(url)) continue;
    seen.add(url);
    rank++;
    // Title: best-effort, take the text between the tag boundary after the href
    const tail = region.slice(m.index, m.index + 400);
    const titleMatch = tail.match(/>([^<]{5,200})</);
    const title =
      titleMatch?.[1].replace(/\s+/g, " ").trim() || new URL(url).hostname;
    out.push({ url, title, rank });
  }
  return out;
}

function persistSnapshot(result: AIOverviewResult): number | null {
  try {
    return writeWithRetry(() => {
      const db = getDatabase();
      const info = db
        .prepare(
          `INSERT INTO ai_overview_tracking
             (query, present, sources, serp_top, fetch_status)
           VALUES (?, ?, ?, ?, ?)`,
        )
        .run(
          result.query,
          result.present ? 1 : 0,
          JSON.stringify(result.sources),
          JSON.stringify(result.serp_top),
          result.fetch_status,
        );
      return typeof info.lastInsertRowid === "bigint"
        ? Number(info.lastInsertRowid)
        : (info.lastInsertRowid as number);
    });
  } catch (err) {
    console.warn(
      `[ai_overview_track] persist failed: ${err instanceof Error ? err.message : err}`,
    );
    return null;
  }
}

export const aiOverviewTrackTool: Tool = {
  name: "ai_overview_track",
  deferred: true,
  riskTier: "low",
  definition: {
    type: "function",
    function: {
      name: "ai_overview_track",
      description: `Track Google AI Overview presence for a search query. Fetches the SERP via stealth browser, detects AI-Overview panel via text + structural heuristics, returns presence + cited sources + top-10 organic results. Persists to ai_overview_tracking.

USE WHEN: user asks "is there an AI overview for…", "track AI overview", "who's getting cited in AI search", "SGE tracking", "generative search panel".

DEGRADES GRACEFULLY: if Google serves an anti-bot interstitial (CAPTCHA / "unusual traffic"), returns fetch_status="blocked" with a clear error. Does NOT throw. Heuristics may miss — compare results with Search Console over time to calibrate.

NOTE: Stealth-scraping Google SERPs may violate Google's Terms of Service. Use for manual, low-volume tracking only. Before wiring this into a scheduled ritual, provision a licensed SERP API (SerpAPI, Serper.dev) to replace the stealthFetch path.

NOT FOR: general web search (use web_search), on-page audits (seo_page_audit), or telemetry (seo_telemetry).`,
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description:
              "Search query to check AI Overview for (natural language).",
          },
          hl: {
            type: "string",
            description:
              "Language code (default 'en'). Examples: 'en', 'es', 'pt'.",
          },
        },
        required: ["query"],
      },
    },
  },

  async execute(args: Record<string, unknown>): Promise<string> {
    const query = String(args.query ?? "").trim();
    // Restrict to valid IETF-like language/region codes — silently clamp to 'en'
    // for unexpected input. Google normalizes invalid codes anyway; validating
    // here keeps the URL predictable.
    const rawHl = String(args.hl ?? "en").trim();
    const hl = /^[a-z]{2,3}(?:-[A-Z]{2,3})?$/.test(rawHl) ? rawHl : "en";
    if (!query) {
      return JSON.stringify({ error: "query parameter is required" });
    }

    const serpUrl = `https://www.google.com/search?q=${encodeURIComponent(query)}&hl=${encodeURIComponent(hl)}`;

    const result: AIOverviewResult = {
      query,
      present: false,
      sources: [],
      serp_top: [],
      fetch_status: "empty",
    };

    await acquireSerpSlot();
    try {
      const fetched = await stealthFetch(serpUrl, {
        timeoutMs: 30_000,
      });
      if (!fetched || !fetched.content) {
        result.fetch_status = "empty";
        result.note =
          "Stealth fetch returned empty. Provision SERP_API_KEY (SerpAPI fallback) for a reliable alternative.";
        persistSnapshot(result);
        return JSON.stringify(result);
      }

      const html = fetched.content;
      if (detectBotBlock(html)) {
        result.fetch_status = "blocked";
        result.note =
          "Google served an anti-bot interstitial. Provision SERP_API_KEY for SerpAPI fallback (follow-up).";
        persistSnapshot(result);
        return JSON.stringify(result);
      }

      const detection = detectAIOverview(html);
      result.present = detection.present;
      result.detection_signal = detection.signal;
      if (detection.present) {
        result.sources = extractAIOverviewSources(html);
      }
      result.serp_top = extractOrganicResults(html);
      result.fetch_status = "ok";

      if (result.serp_top.length === 0) {
        result.fetch_status = "parse_error";
        result.note =
          "SERP fetched but no organic results parsed — Google DOM may have changed; heuristics need refresh.";
      }
    } catch (err) {
      result.fetch_status = "parse_error";
      result.note = err instanceof Error ? err.message : String(err);
    } finally {
      releaseSerpSlot();
    }

    const snapshotId = persistSnapshot(result);
    return JSON.stringify({ ...result, snapshot_id: snapshotId ?? undefined });
  },
};

export const _testonly = {
  detectAIOverview,
  detectBotBlock,
  extractOrganicResults,
  extractAIOverviewSources,
};
