/**
 * Shared adapter types for the Mission Control framework adapter system.
 *
 * These types replace the loose `Record<string, unknown>` patterns from the
 * original adapters with properly typed payloads, enums, and interfaces.
 */

// ---------------------------------------------------------------------------
// Agent Status
// ---------------------------------------------------------------------------

/** Discrete agent lifecycle states. */
export enum AgentStatus {
  /** Agent has registered but has not yet sent a heartbeat. */
  Registered = "registered",
  /** Agent is connected and ready to accept work. */
  Online = "online",
  /** Agent is connected but not actively working. */
  Idle = "idle",
  /** Agent is actively executing a task. */
  Busy = "busy",
  /** Agent encountered a recoverable error. */
  Error = "error",
  /** Agent has disconnected or stopped sending heartbeats. */
  Offline = "offline",
}

// ---------------------------------------------------------------------------
// Capabilities
// ---------------------------------------------------------------------------

/** Well-known agent capabilities. Frameworks may extend with custom strings. */
export type BuiltinCapability =
  | "planning"
  | "coding"
  | "research"
  | "review"
  | "testing"
  | "debugging"
  | "deployment"
  | "documentation"
  | "refactoring"
  | "security-audit";

/**
 * Agent capabilities descriptor.
 * `builtins` are well-known capabilities recognized by the scheduler.
 * `custom` allows framework-specific extensions without type widening.
 */
export interface AgentCapabilities {
  readonly builtins: ReadonlyArray<BuiltinCapability>;
  readonly custom?: ReadonlyArray<string>;
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

/** Payload sent by an agent when it first connects. */
export interface AgentRegistration {
  /** Unique agent identifier (typically `framework:name` or a UUID). */
  readonly agentId: string;
  /** Human-readable display name. */
  readonly name: string;
  /** Framework that produced this agent (e.g. "prometheus", "crewai"). */
  readonly framework: string;
  /** Agent capabilities for task routing. */
  readonly capabilities?: AgentCapabilities;
  /** Model identifier the agent is using (e.g. "claude-opus-4-20250514"). */
  readonly model?: string;
  /** Arbitrary framework-specific metadata. */
  readonly metadata?: Readonly<Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// Heartbeat
// ---------------------------------------------------------------------------

/** Typed heartbeat payload replacing the untyped `metrics` bag. */
export interface HeartbeatPayload {
  /** Agent sending the heartbeat. */
  readonly agentId: string;
  /** Current status. */
  readonly status: AgentStatus;
  /** ISO-8601 timestamp when the heartbeat was generated by the agent. */
  readonly timestamp: string;
  /** Framework-specific metrics (typed per-adapter via generics or override). */
  readonly metrics?: Readonly<Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// Assignments
// ---------------------------------------------------------------------------

/** Priority levels for task assignments, lower number = higher priority. */
export enum AssignmentPriority {
  Critical = 0,
  High = 1,
  Medium = 2,
  Low = 3,
}

/** A task assignment returned to an agent polling for work. */
export interface Assignment {
  /** Task ID (string for cross-system portability). */
  readonly taskId: string;
  /** Task description / instructions. */
  readonly description: string;
  /** Numeric priority (0 = critical). */
  readonly priority: AssignmentPriority;
  /** Optional due date as ISO-8601 string. */
  readonly dueDate?: string;
  /** Arbitrary metadata for the consuming framework. */
  readonly metadata?: Readonly<Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// Task Reports
// ---------------------------------------------------------------------------

/** Phase within the Plan-Execute-Reflect loop (Prometheus-specific, optional). */
export type TaskPhase =
  | "planning"
  | "executing"
  | "reflecting"
  | "completed"
  | "failed";

/** Report sent by an agent about task progress. */
export interface TaskReport {
  /** The task being reported on. */
  readonly taskId: string;
  /** The reporting agent. */
  readonly agentId: string;
  /** Progress percentage (0-100). */
  readonly progress: number;
  /** Current task status string. */
  readonly status: string;
  /** Current phase (optional, Prometheus agents send this). */
  readonly phase?: TaskPhase;
  /** Task output / result payload. */
  readonly output?: unknown;
  /** Error message if the task failed. */
  readonly errorMessage?: string;
}

// ---------------------------------------------------------------------------
// Adapter Lifecycle Events
// ---------------------------------------------------------------------------

/** Events emitted during adapter lifecycle transitions. */
export enum AdapterLifecycleEvent {
  /** Agent registered successfully. */
  AgentRegistered = "adapter.agent_registered",
  /** Heartbeat received and processed. */
  HeartbeatReceived = "adapter.heartbeat_received",
  /** Task report processed. */
  TaskReported = "adapter.task_reported",
  /** Agent disconnected. */
  AgentDisconnected = "adapter.agent_disconnected",
  /** Adapter validation failed. */
  ValidationFailed = "adapter.validation_failed",
}

/** Payload shape for adapter lifecycle events. */
export interface AdapterEvent {
  readonly event: AdapterLifecycleEvent;
  readonly framework: string;
  readonly agentId: string;
  readonly timestamp: number;
  readonly detail?: Readonly<Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// Framework Metadata
// ---------------------------------------------------------------------------

/** Metadata describing a framework adapter's identity and features. */
export interface FrameworkMetadata {
  /** Framework identifier (e.g. "prometheus", "crewai"). */
  readonly name: string;
  /** Semantic version of the adapter. */
  readonly version: string;
  /** Human-readable description. */
  readonly description?: string;
  /** Feature flags supported by this adapter. */
  readonly features: ReadonlyArray<string>;
}

// ---------------------------------------------------------------------------
// Framework Adapter Interface
// ---------------------------------------------------------------------------

/**
 * Contract that every framework adapter must implement.
 *
 * The `DefaultAdapter` base class provides a full implementation of this
 * interface. Framework-specific adapters extend the base and override
 * the protected transform/hook methods.
 */
export interface FrameworkAdapter {
  /** The framework this adapter handles. */
  readonly framework: string;
  /** Metadata about this adapter. */
  readonly metadata: FrameworkMetadata;

  /** Register a new agent. */
  register(agent: AgentRegistration): Promise<void>;
  /** Process a heartbeat from an agent. */
  heartbeat(payload: HeartbeatPayload): Promise<void>;
  /** Process a task progress report. */
  reportTask(report: TaskReport): Promise<void>;
  /** Get pending assignments for an agent. */
  getAssignments(agentId: string): Promise<Assignment[]>;
  /** Disconnect an agent gracefully. */
  disconnect(agentId: string): Promise<void>;
}
