/**
 * F8 Paper Trading — shared venue-adapter domain model.
 *
 * Per Nautilus research-to-live parity: every execution venue (paper equity,
 * pm-trader MCP, Binance live, Polymarket live) implements this surface. A
 * strategy that runs in paper today runs in live tomorrow without refactor.
 *
 * v1 is intentionally minimal — MARKET orders + day-TIF only. LIMIT/STOP/FOK
 * and order-book access are F8.2+. Keeping the v1 interface small forces
 * every adapter to implement exactly what the weekly-rebalance loop needs.
 */

import type { Clock } from "./clock.js";

export type OrderSide = "buy" | "sell";
export type OrderType = "market";
export type TimeInForce = "day";

export interface Order {
  /** UUID generated by the caller (rebalance executor). */
  clientOrderId: string;
  symbol: string;
  side: OrderSide;
  /** Fractional shares allowed; 4dp precision used elsewhere. */
  quantity: number;
  type: OrderType;
  timeInForce: TimeInForce;
}

export interface Fill {
  /** UUID issued by the adapter on accept. */
  fillId: string;
  clientOrderId: string;
  symbol: string;
  side: OrderSide;
  quantity: number;
  /** Price after slippage; what the position actually pays / earns per share. */
  price: number;
  /** quantity × price. Positive regardless of side. */
  grossNotional: number;
  /** Per-fill commission charge (currency units). */
  commission: number;
  /** Round-trip bps charged as slippage (one-sided). */
  slippageBps: number;
  /** ISO 8601 timestamp from the adapter's clock. */
  filledAt: string;
}

export interface OrderReject {
  clientOrderId: string;
  /** Stable enum string: "insufficient_cash" | "no_quote" | "short_sell" | "zero_quantity" | "stale_price" | ... */
  reason: string;
  /** ISO 8601 timestamp from the adapter's clock. */
  rejectedAt: string;
}

/** Convenient result type for `placeOrder`. */
export type OrderResult = Fill | OrderReject;

export function isFill(r: OrderResult): r is Fill {
  return "fillId" in r;
}

export function isOrderReject(r: OrderResult): r is OrderReject {
  return "reason" in r && !("fillId" in r);
}

/**
 * Common fields every Position variant carries regardless of asset class.
 * Use via the `Position` discriminated union below — don't reference this
 * type directly outside `venue-types.ts`.
 */
interface PositionCommon {
  shares: number;
  /** Weighted-average entry price over all open buys. Equity: USD/share; PM: USDC/share (≤ 1). */
  avgCost: number;
  /** Latest quote × shares (computed by adapter, not stored). */
  marketValue: number;
  /** marketValue − shares × avgCost. Can be negative. */
  unrealizedPnl: number;
  /**
   * True when the adapter could not obtain a fresh quote and fell back to
   * `avg_cost`. Downstream callers must treat `marketValue` / `unrealizedPnl`
   * as unreliable for stale rows.
   */
  stale: boolean;
}

/** Equity position (PaperEquityAdapter). */
export interface EquityPosition extends PositionCommon {
  kind: "equity";
  symbol: string;
}

/** Polymarket prediction-market position (PolymarketPaperAdapter). F8.1b. */
export interface PolymarketPosition extends PositionCommon {
  kind: "polymarket";
  marketId: string;
  outcome: string; // "Yes" | "No" | custom label
  slug: string | null;
  tokenId: string | null;
}

/**
 * Discriminated union across all venues. Callers narrow via `p.kind`.
 *
 * Backwards compat note: existing code that read `position.symbol` must now
 * type-guard with `if (p.kind === "equity")`. This is intentional — forces
 * explicit handling of multi-venue portfolios.
 */
export type Position = EquityPosition | PolymarketPosition;

/** Narrow a Position to the equity variant. */
export function isEquityPosition(p: Position): p is EquityPosition {
  return p.kind === "equity";
}

/** Narrow a Position to the Polymarket variant. */
export function isPolymarketPosition(p: Position): p is PolymarketPosition {
  return p.kind === "polymarket";
}

export interface Balance {
  cash: number;
  /** Σ Position.marketValue over all open positions. */
  positionsValue: number;
  /** cash + positionsValue. */
  totalEquity: number;
}

export interface MarketQuote {
  symbol: string;
  /** Last observed price used for fills + mark-to-market. */
  price: number;
  /** ISO 8601 timestamp of the price observation. */
  asOf: string;
  /** Provenance so callers can judge staleness. */
  source: "weekly_close" | "intraday_quote" | "cache";
}

export interface GetFillsOpts {
  /** ISO 8601; only include fills strictly after this time. */
  since?: string;
  symbol?: string;
  /** Default applied by the adapter; no required floor. */
  limit?: number;
}

export interface VenueAdapter {
  /** Stable name; e.g. "paper_equity" / "pm_trader" / "binance_live". */
  readonly name: string;
  /** Time source. Strategies must read clock.now() — never `new Date()` directly. */
  readonly clock: Clock;

  getMarketData(symbol: string): Promise<MarketQuote>;
  placeOrder(order: Order): Promise<OrderResult>;
  getPositions(): Promise<Position[]>;
  getBalance(): Promise<Balance>;
  getFills(opts?: GetFillsOpts): Promise<Fill[]>;
}
