#!/usr/bin/env bash
# Build docs artifacts: llms-full.txt, llms.txt, index.html
# Zero deps — pure bash. Run via: npm run docs
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/public/docs"
DOCS="$ROOT/docs"

mkdir -p "$OUT"

# ---------------------------------------------------------------------------
# 1. llms-full.txt — concatenated project docs for LLM context
# ---------------------------------------------------------------------------
{
  echo "# Mission Control — Full Project Documentation"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""

  # Root docs first (most important context)
  for f in README.md CLAUDE.md; do
    if [ -f "$ROOT/$f" ]; then
      echo "================================================================================"
      echo "# FILE: $f"
      echo "================================================================================"
      echo ""
      cat "$ROOT/$f"
      echo ""
      echo ""
    fi
  done

  # All docs/*.md (sorted for consistency)
  for f in $(find "$DOCS" -maxdepth 1 -name "*.md" -type f | sort); do
    name="$(basename "$f")"
    echo "================================================================================"
    echo "# FILE: docs/$name"
    echo "================================================================================"
    echo ""
    cat "$f"
    echo ""
    echo ""
  done
} > "$OUT/llms-full.txt"

# ---------------------------------------------------------------------------
# 2. llms.txt — index file (llmstxt.org format)
# ---------------------------------------------------------------------------
{
  echo "# Mission Control"
  echo "> Unified AI agent orchestrator. Jarvis strategic assistant."
  echo ""
  echo "## Root"
  echo "- [README](README.md): Project overview, architecture, setup"
  echo "- [CLAUDE.md](CLAUDE.md): Development instructions, invariants, patterns"
  echo ""
  echo "## Docs"
  for f in $(find "$DOCS" -maxdepth 1 -name "*.md" -type f | sort); do
    name="$(basename "$f")"
    title="$(head -5 "$f" | grep "^# " | head -1 | sed 's/^# //' || echo "$name")"
    echo "- [$name](docs/$name): $title"
  done
} > "$OUT/llms.txt"

# ---------------------------------------------------------------------------
# 3. index.html — minimal browsable docs page
# ---------------------------------------------------------------------------
TOTAL_DOCS=$(find "$DOCS" -maxdepth 1 -name "*.md" -type f | wc -l)
cat > "$OUT/index.html" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mission Control — Docs</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 48px 24px; line-height: 1.6; }
  .container { max-width: 720px; margin: 0 auto; }
  h1 { font-size: 28px; font-weight: 700; color: #f8fafc; margin-bottom: 8px; }
  .subtitle { color: #94a3b8; font-size: 14px; margin-bottom: 32px; }
  .section { margin-bottom: 32px; }
  .section-title { font-size: 13px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 12px; }
  .doc-list { list-style: none; }
  .doc-list li { margin-bottom: 8px; }
  .doc-list a { color: #60a5fa; text-decoration: none; font-size: 15px; padding: 8px 12px; display: block; border-radius: 6px; border: 1px solid transparent; transition: all 0.15s; }
  .doc-list a:hover { background: #1e293b; border-color: #334155; color: #93c5fd; }
  .doc-list .desc { color: #64748b; font-size: 12px; margin-top: 2px; }
  .llm-links { display: flex; gap: 12px; margin-top: 24px; }
  .llm-links a { font-size: 12px; color: #94a3b8; text-decoration: none; padding: 6px 12px; border: 1px solid #334155; border-radius: 4px; }
  .llm-links a:hover { border-color: #60a5fa; color: #60a5fa; }
  footer { margin-top: 48px; color: #475569; font-size: 12px; text-align: center; }
</style>
</head>
<body>
<div class="container">
  <h1>Mission Control</h1>
  <p class="subtitle">Agent orchestrator documentation</p>

  <div class="section">
    <div class="section-title">Project Root</div>
    <ul class="doc-list">
      <li><a href="/docs/raw/README.md">README.md<div class="desc">Project overview, architecture, setup</div></a></li>
      <li><a href="/docs/raw/CLAUDE.md">CLAUDE.md<div class="desc">Development instructions, invariants, patterns</div></a></li>
    </ul>
  </div>

  <div class="section">
    <div class="section-title">Documentation</div>
    <ul class="doc-list" id="docs"></ul>
  </div>

  <div class="llm-links">
    <a href="/docs/llms.txt">llms.txt</a>
    <a href="/docs/llms-full.txt">llms-full.txt</a>
  </div>

  <footer>Generated by build-docs.sh</footer>
</div>
<script>
HTMLEOF

# Inject doc entries dynamically
echo "const docs = [" >> "$OUT/index.html"
for f in $(find "$DOCS" -maxdepth 1 -name "*.md" -type f | sort); do
  name="$(basename "$f")"
  title="$(head -5 "$f" | grep "^# " | head -1 | sed 's/^# //' | sed "s/'/\\\\'/g" || echo "$name")"
  echo "  {name:'$name', title:'$title'}," >> "$OUT/index.html"
done
cat >> "$OUT/index.html" << 'HTMLEOF2'
];
const ul = document.getElementById('docs');
docs.forEach(d => {
  const li = document.createElement('li');
  li.innerHTML = `<a href="/docs/raw/${d.name}">${d.name}<div class="desc">${d.title}</div></a>`;
  ul.appendChild(li);
});
</script>
</body>
</html>
HTMLEOF2

echo "[build-docs] Generated: $OUT/llms-full.txt ($(wc -c < "$OUT/llms-full.txt") bytes), llms.txt, index.html ($TOTAL_DOCS docs)"
