#!/usr/bin/env bash
# preview-caddy-sync — self-serve demo previews (added 2026-08-23).
#
# Regenerates /etc/caddy/previews-generated.caddy from the subdirectories of
# /root/claude/previews using a FIXED template, validates, and reloads Caddy.
# Triggered by preview-caddy-sync.path whenever a preview dir is added/removed.
#
# Trust boundary: Jarvis (mission-control shell_exec) may create
# /root/claude/previews/<name>/ but cannot write /etc. Only the sanitized dir
# NAME crosses into Caddy config — never config content. Names must match
# ^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$ and must not collide with an existing
# explicit vhost (RESERVED below; anything else is caught by caddy validate,
# which reverts the generated file).
set -euo pipefail

PREVIEWS_ROOT=/root/claude/previews
OUT=/etc/caddy/previews-generated.caddy
CADDYFILE=/etc/caddy/Caddyfile
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# First labels of vhosts that already have explicit blocks in the Caddyfile.
RESERVED=" intel-demo longevidad-demo lite-demo vlmp-demo aura-dash bariatrica "

{
  echo "# GENERATED by preview-caddy-sync.sh — DO NOT EDIT."
  echo "# One static file_server vhost per directory under ${PREVIEWS_ROOT}."
  for dir in "${PREVIEWS_ROOT}"/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    [[ "$name" =~ ^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$ ]] || continue
    case "$RESERVED" in *" $name "*) continue ;; esac
    printf '\n%s.187.77.25.101.nip.io {\n' "$name"
    printf '\tencode zstd gzip\n'
    printf '\theader {\n'
    printf '\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"\n'
    printf '\t\tX-Content-Type-Options "nosniff"\n'
    printf '\t\tReferrer-Policy "strict-origin-when-cross-origin"\n'
    printf '\t}\n'
    printf '\troot * %s/%s\n' "$PREVIEWS_ROOT" "$name"
    printf '\tfile_server\n'
    printf '}\n'
  done
} > "$TMP"

# No change → nothing to do (path unit fires on every dir touch).
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
  exit 0
fi

# Swap in the new file, keeping the previous one for revert-on-invalid.
if [ -f "$OUT" ]; then cp "$OUT" "${OUT}.prev"; fi
install -m 644 "$TMP" "$OUT"

if ! caddy validate --config "$CADDYFILE" > /dev/null 2>&1; then
  echo "preview-caddy-sync: caddy validate FAILED — reverting ${OUT}" >&2
  if [ -f "${OUT}.prev" ]; then
    install -m 644 "${OUT}.prev" "$OUT"
  else
    printf '# empty (last generation failed validation)\n' > "$OUT"
  fi
  exit 1
fi

systemctl reload caddy
echo "preview-caddy-sync: reloaded caddy with $(grep -c 'nip.io {' "$OUT") preview vhost(s)"
